services:
  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: quit4real
    volumes:
      - ./data:/app/data        # Persist database
      - ./logs:/app/logs        # Mount logs directory instead of a file
    working_dir: /app
    command: [ "./quit4real.today" ]
