services:
  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: quit4real
    volumes:
      - app-data:/app
    working_dir: /app
    command: [ "./quit4real.today" ]

volumes:
  app-data:
