name: Go

on:
  push:
    branches: [ "src" ]
  pull_request:
    branches: [ "src" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Rename example config
        run: mv config/.example.config.go config/config.go

      - name: Build
        run: go build -v
